services:
  - type: web
    name: playlist-converter
    env: docker
    plan: free
    healthCheckPath: /api/health
    envVars:
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: PYTHON_VERSION
        value: "3.9"
      - key: ALLOW_ORIGINS
        value: "*" 