services:
  - type: web
    name: playlist-converter
    env: docker
    plan: free
    healthCheckPath: /api/health
    envVars:
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: PYTHON_VERSION
        value: "3.9"
      - key: ALLOW_ORIGINS
        value: "*"
      - key: PORT
        value: "8080"
      - key: RENDER
        value: "true"
      - key: SELENIUM_HEADLESS
        value: "true"
      - key: CHROMEDRIVER_FLAGS
        value: "--no-sandbox --disable-dev-shm-usage --disable-gpu" 